# Keepalived 2.4.1 — Node A (10.30.13.12) — MASTER
# Referensi: https://www.keepalived.org/documentation/keepalived-conf/

global_defs {
    router_id PGHA_A
    enable_script_security
}

vrrp_script check_haproxy {
    script "/usr/bin/killall -0 haproxy"
    interval 2
    weight 2
    fall 2
    rise 2
}

vrrp_instance VI_PG {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 150
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass pgcluster99
    }
    virtual_ipaddress {
        10.30.13.15/24
    }
    track_script {
        check_haproxy
    }
    notify_master "/usr/bin/systemctl reload haproxy"
}
