# Patroni 4.1.3 — Node D (10.30.13.10) — Leader Candidate
# Referensi: https://patroni.readthedocs.io/en/latest/yaml_configuration.html

scope: pg_cluster
namespace: /db/
name: node-d

restapi:
    listen: 10.30.13.10:8008
    connect_address: 10.30.13.10:8008

etcd3:
    hosts:
        - 10.30.13.12:2379
        - 10.30.13.13:2379
        - 10.30.13.14:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            parameters:
                max_connections: 200
                max_prepared_transactions: 0
                wal_level: replica
                hot_standby: "on"
                max_wal_senders: 10
                max_replication_slots: 10
                wal_log_hints: "on"
                shared_buffers: 256MB

    initdb:
        - encoding: UTF8
        - data-checksums

    users:
        groupware:
            password: 'KBBgroupware@2025!'
            options:
                - createrole

    pg_hba:
        - host replication replicator 10.30.13.0/24 md5
        - host all groupware 10.30.13.0/24 md5
        - host all postgres 127.0.0.1/32 trust

postgresql:
    listen: 10.30.13.10:5432
    connect_address: 10.30.13.10:5432
    data_dir: /var/lib/pgsql/16/data
    bin_dir: /usr/pgsql-16/bin
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: replicator_pass
        superuser:
            username: postgres
            password: postgres_pass
        rewind:
            username: rewind_user
            password: rewind_pass
    parameters:
        unix_socket_directories: /var/run/postgresql

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
