[pg_cluster]
pg1-path=/var/lib/pgsql/16/data
pg1-port=5432
repo1-path=/backup/pgbackrest
repo1-retention-full=4
repo1-retention-diff=4
repo1-cipher-type=none

[global]
log-level-console=info
log-level-file=detail
compress-type=gz
process-max=2
